### ISSUE TITLE
PC端整体界面好难看

### ISSUE THREAD

**Issue by aunhappy** [lwyj123/wuanlife#64]
感觉和UI的画风差的不是一点点啊
![image](https://cloud.githubusercontent.com/assets/15842120/26753306/2c4f0ce2-4896-11e7-8a50-66ba24b31f7e.png)
这是什么原因？样式没加载还是咋的了

**Comment by lwyj123** [comment]
设计稿定宽的，做的时候要考虑自适应，改了下你现在再看看
